// 自动生成的模式配置 - 55个模式
export const MODES: Record<string, {label: string, desc: string, icon: string, category: string}> = {
  "auto": {"label": "自动判断", "desc": "根据问题自动选择策略", "icon": "🤖", "category": "auto"},
  "explore": {"label": "自由探索", "desc": "开放心态，引导用户自己发现", "icon": "🔍", "category": "explore"},
  "analyze": {"label": "深度分析", "desc": "拆解多维度，找核心矛盾", "icon": "🎯", "category": "explore"},
  "research": {"label": "调研查询", "desc": "信息来源和获取路径", "icon": "📚", "category": "explore"},
  "validate": {"label": "验证确认", "desc": "梳理假设，验证方法", "icon": "✅", "category": "explore"},
  "simulate": {"label": "情景模拟", "desc": "推演不同路径的发展", "icon": "🔮", "category": "explore"},
  "advise": {"label": "专业建议", "desc": "具体可执行的建议", "icon": "💼", "category": "decision"},
  "consult": {"label": "咨询建议", "desc": "专业咨询，给出方案", "icon": "💡", "category": "decision"},
  "evaluate": {"label": "方案评估", "desc": "优缺点分析，综合评分", "icon": "⚖️", "category": "decision"},
  "plan": {"label": "规划制定", "desc": "分阶段计划，里程碑", "icon": "📋", "category": "decision"},
  "roadmap": {"label": "路线图", "desc": "长期愿景，演进路径", "icon": "🗺️", "category": "decision"},
  "brainstorm": {"label": "头脑风暴", "desc": "发散思维，多方向创意", "icon": "🧠", "category": "creative"},
  "design": {"label": "设计思维", "desc": "创意发散，用户中心", "icon": "🎨", "category": "creative"},
  "innovation": {"label": "创新工坊", "desc": "突破常规，快速原型", "icon": "🚀", "category": "creative"},
  "random": {"label": "随机联想", "desc": "跨界思维，打破常规", "icon": "🎲", "category": "creative"},
  "future": {"label": "未来推演", "desc": "预测趋势，前瞻布局", "icon": "🔭", "category": "creative"},
  "roleplay": {"label": "角色扮演", "desc": "模拟场景，沉浸体验", "icon": "🎭", "category": "creative"},
  "critique": {"label": "批判评估", "desc": "找漏洞，挑毛病", "icon": "⚡", "category": "critique"},
  "devil": {"label": "魔鬼代言", "desc": "专挑毛病，stress test", "icon": "😈", "category": "critique"},
  "redteam": {"label": "红队演练", "desc": "安全攻防，找弱点", "icon": "🛡️", "category": "critique"},
  "peer": {"label": "同行评审", "desc": "学术评议，专业把关", "icon": "📄", "category": "critique"},
  "collab": {"label": "协作共创", "desc": "互相补充，完善观点", "icon": "🤝", "category": "collaborate"},
  "debate": {"label": "对抗辩论", "desc": "互相反驳，找漏洞", "icon": "⚔️", "category": "collaborate"},
  "puzzle": {"label": "拼图模式", "desc": "拼合观点，完整图景", "icon": "🧩", "category": "collaborate"},
  "balance": {"label": "利弊权衡", "desc": "优缺点分析，平衡视角", "icon": "⚖️", "category": "collaborate"},
  "global": {"label": "全球视角", "desc": "跨文化观点，多元视角", "icon": "🌐", "category": "collaborate"},
  "learn": {"label": "知识学习", "desc": "基础概念，进阶路径", "icon": "📖", "category": "learn"},
  "mentor": {"label": "导师问答", "desc": "一问一答，深度指导", "icon": "👨‍🏫", "category": "learn"},
  "socratic": {"label": "苏格拉底", "desc": "连环追问，启发思考", "icon": "❓", "category": "learn"},
  "onboarding": {"label": "新人培训", "desc": "基础知识，避坑指南", "icon": "🎓", "category": "learn"},
  "troubleshoot": {"label": "问题诊断", "desc": "根因分析，解决方案", "icon": "🔧", "category": "practical"},
  "optimize": {"label": "优化改进", "desc": "识别瓶颈，量化效果", "icon": "⚙️", "category": "practical"},
  "case": {"label": "案例分析", "desc": "实例研讨，经验萃取", "icon": "💼", "category": "practical"},
  "workshop": {"label": "工作坊", "desc": "动手实践，步骤指导", "icon": "🛠️", "category": "practical"},
  "demo": {"label": "产品演示", "desc": "场景数据，价值亮点", "icon": "🎬", "category": "practical"},
  "grooming": {"label": "需求梳理", "desc": "用户故事，验收标准", "icon": "📝", "category": "practical"},
  "standup": {"label": "站会", "desc": "进展同步，阻塞协调", "icon": "📢", "category": "practical"},
  "sprint": {"label": "冲刺规划", "desc": "目标交付，任务拆分", "icon": "🏃", "category": "practical"},
  "consensus": {"label": "寻求共识", "desc": "汇总观点，折中方案", "icon": "🤝", "category": "strategy"},
  "interview": {"label": "专家访谈", "desc": "主持提问，深入阐述", "icon": "🎙️", "category": "strategy"},
  "panel": {"label": "圆桌论坛", "desc": "行业案例，互动观点", "icon": "🏛️", "category": "strategy"},
  "review": {"label": "项目评审", "desc": "进度质量，调整建议", "icon": "📊", "category": "strategy"},
  "pitch": {"label": "路演答辩", "desc": "商业模式，投资建议", "icon": "🎯", "category": "strategy"},
  "crisis": {"label": "危机处理", "desc": "应急响应，恢复计划", "icon": "🚨", "category": "strategy"},
  "retrospective": {"label": "复盘会议", "desc": "成败因素，方法论", "icon": "🔍", "category": "strategy"},
  "philosophy": {"label": "哲学探讨", "desc": "深层思考，思辨反思", "icon": "🤔", "category": "strategy"},
  "growth": {"label": "增长黑客", "desc": "漏斗分析，实验设计", "icon": "📈", "category": "strategy"},
  "security": {"label": "安全审查", "desc": "风险合规，整改措施", "icon": "🔒", "category": "strategy"},
  "merger": {"label": "并购整合", "desc": "战略价值，整合路线", "icon": "🏗️", "category": "strategy"},
  "spinoff": {"label": "分拆决策", "desc": "可行性分析，实施计划", "icon": "✂️", "category": "strategy"},
  "partnership": {"label": "合作洽谈", "desc": "互补性分析，利益分配", "icon": "🤝", "category": "strategy"},
  "reorg": {"label": "组织重构", "desc": "效率诊断，变革管理", "icon": "🏢", "category": "strategy"},
  "budget": {"label": "预算规划", "desc": "趋势分析，成本控制", "icon": "💰", "category": "strategy"},
  "talent": {"label": "人才盘点", "desc": "能力评估，培养计划", "icon": "👥", "category": "strategy"},
  "culture": {"label": "文化建设", "desc": "价值观，落地机制", "icon": "🌱", "category": "strategy"},
  "values": {"label": "价值对齐", "desc": "目标梳理，冲突解决", "icon": "🎯", "category": "strategy"}
};

export const MODE_CATEGORIES: Record<string, {label: string, modes: string[]}> = {
  "auto": {"label": "🤖 智能推荐", "modes": ["auto"]},
  "explore": {"label": "🔍 探索分析", "modes": ["explore", "analyze", "research", "validate", "simulate"]},
  "decision": {"label": "💡 建议决策", "modes": ["advise", "consult", "evaluate", "plan", "roadmap"]},
  "creative": {"label": "🎨 创新创意", "modes": ["brainstorm", "design", "innovation", "random", "future", "roleplay"]},
  "critique": {"label": "⚡ 批判评估", "modes": ["critique", "devil", "redteam", "peer"]},
  "collaborate": {"label": "🤝 协作共创", "modes": ["collab", "debate", "puzzle", "balance", "global"]},
  "learn": {"label": "📖 学习成长", "modes": ["learn", "mentor", "socratic", "onboarding"]},
  "practical": {"label": "🛠️ 实战应用", "modes": ["troubleshoot", "optimize", "case", "workshop", "demo", "grooming", "standup", "sprint"]},
  "strategy": {"label": "🎯 战略决策", "modes": ["consensus", "interview", "panel", "review", "pitch", "crisis", "retrospective", "philosophy", "growth", "security", "merger", "spinoff", "partnership", "reorg", "budget", "talent", "culture", "values"]}
};

// 各场景适用的模式
export const SCENE_MODES = {
  brainstorm: ["auto", "debate", "collab", "mentor", "socratic", "devil", "roleplay", "peer", "case", "design", "redteam", "future", "random", "puzzle", "balance", "global"],
  chat: ["auto", "explore", "analyze", "research", "validate", "simulate", "advise", "consult", "evaluate", "plan", "roadmap", "brainstorm", "design", "innovation", "critique", "troubleshoot", "optimize", "case", "workshop", "demo", "grooming", "standup", "sprint", "learn", "mentor", "socratic", "onboarding"],
  roundtable: ["auto", "consensus", "interview", "panel", "review", "pitch", "crisis", "retrospective", "philosophy", "growth", "security", "merger", "spinoff", "partnership", "reorg", "budget", "talent", "culture", "values", "debate", "collab"]
};
